/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ycl_ndkdemo_jni_JniCore */

#ifndef _Included_com_ycl_ndkdemo_jni_JniCore
#define _Included_com_ycl_ndkdemo_jni_JniCore
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ycl_ndkdemo_jni_JniCore
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_ycl_ndkdemo_jni_JniCore_add
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_ycl_ndkdemo_jni_JniCore
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ycl_ndkdemo_jni_JniCore_getString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
